In [29]:
# Variables

# This is a comment - any code commented out is not run -
# meaning that any code or text commented out is ignored.

#"""
#his is a multi-line comment
#You can comment out many lines at once.
#For the most part you will see single line comments
#but it is good to see this.
#As in single line comments, any code contained within multi-line comments are not run -
#meaning that any code commented out is ignored.
#"""

# Topic: Strings

# Create a variable named `subject` with no value (None).

# Assign a value of "Programmers to the variable `subject`.


# Create a variable, `first_name`, and assign it a value of an empty string.


# Assign a value of "Ada" to the variable `first_name`.

subject = ""
subject = "Programmers"
first_name = ""
first_name = "Ada"
last_name = "Lovelace"
full_name = first_name, last_name
profession = "Computer Programmer"
known_for = "First Computer Programmer"
first_algorithm = "Analytical Engine"
city_location = "London"
country_location = "England"
nationality = "British"

# Create a variable, `last_name`, and assign it a value of a string, "Lovelace".


# Create a variable, `full_name`, and assign it a value of the combination of `first_name` and `last_name` with a space.


# Create a variable, `profession`, and assign it a value of a string, "Computer Programmer".


# Create a variable, `known_for`, and assign it a value of a string, "First Computer Programmer".


# Create a variable, `first_algorithm`, and assign it a value of a string, "Analytical Engine".


# Create a variable, `city_location`, and assign it a value of a string, "London".


# Create a variable, `country_location`, and assign it a value of a string, "England".


# Create a variable, `nationality`, and assign it a value of a string, "British".



# Topic: Integers
birth_year = 1815
death_year = 1852
age_at_passing = death_year - birth_year
year_of_publish = 1842

# Create a variable, `birth_year`, and assign it with an integer of 1815.


# Create a variable, `death_year`, and assign it with an integer of 1852.


# Create a variable, `age_at_passing`, and assign it a value of death_year minus birth_year.


# Create a variable, `year_of_publish`, and assign it with an integer of 1842.



#Topic: Print

# Print: "First Name: " and `first_name`.

print("First name:" + first_name)
      
# Print: "Last Name: " and `last_name`.

print("Last name:" + last_name)
# Print: "Profession: " and `profession`.


# Print: "BirthYear: " and `birth_year`.
print("Birth year: " + str(birth_year))


#Topic: Concat Values

# Create and print a variable, `statement_one`, by assigning it a value of a concatenated string:
# "Programmers: Ada Lovelace is a British Computer Programmer born in 1815."
statement_one = "Programmers: " + first_name + " " + last_name + " is a " + nationality + " " + profession
print(statement_one)
# Create and print a variable, `statement_two`, by assigning it a value of a concatenated string:
# "She is commonly referred to as the First Computer Programmer."
statement_two = statement_one + " She is commonly referred to as the " + known_for
print(statement_two)


# Create and print a variable, `statement_three`, by assigning it a value of a concatenated string:
# "In 1842 she published the first Algorithm, the Analytical Engine, at the age of 27."
statement_three = "In " + str(year_of_publish) + " she published the first algorithm, " + str(first_algorithm) + " at the age of 27"
print(statement_three)


# Create and print a variable, `statement_four`, by assigning it a value of a concatenated string:
# "She was a British Citizen who lived in London, England until her passing in 1852 at the age of 37."
statement_four = "She was a " + nationality + " Citizen who lived in " + city_location + "," + country_location + " until her passsing in " + str(death_year) + " at the age of " + str(age_at_passing) 
print(statement_four)

First name:Ada
Last name:Lovelace
Birth year: 1815
Programmers: Ada Lovelace is a British Computer Programmer
Programmers: Ada Lovelace is a British Computer Programmer She is commonly referred to as the First Computer Programmer
In 1842 she published the first algorithm, Analytical Engine at the age of 27
She was a British Citizen who lived in London,England until her passsing in 1852 at the age of 37

In [57]:
# Create a list called 'farm' with the elements "pig", "cow", "chicken", "dog", "horse", "sheep".

farm = ["pig","cow","chicken","dog","horse","sheep"]
a = farm[0]
b = "godzilla"
c = "Mothra"
print(a)
print(b)


if a != b:
    print("rwar")
elif farm[5] == "Mothra":
    print("Screech")
else:
    print("This animal is neither Godzilla or Mothra!")

pig
godzilla
rwar

In [ ]:
# Write an if statement that prints the string "RWAR!" if the first element of farm is NOT "Godzilla".

# Write an else if statement that prints the string "SCREECH!" if the last element of farm is "Mothra".

# Else, print the string "This animal is neither Godzilla nor Mothra!".


# Declare a variable named 'dog' with a string of "Spot".

# Declare 3 variables `cat`, `city`, `car` without assigning them values.


# Assign the string "Farley" to `cat`.


# Assign the string "San Francisco" to `city`.


# Assign the string "Prius" to `car`.


# Using string concatenation, print out the sentence "See Spot run!".


# Using string concatenation, print out the sentence "I drive Farley around San Francisco in my Prius".


# Declare a variable budget and assign it a value of 5000.


# Declare a variable rent_cost and assign it a value of 1500.


# Declare a variable utilities_cost and assign it a value of 150.


# Declare a variable food_cost and assign it a value of 250.


# Declare a variable transportation_cost and assign it a value of 350.


# Declare a variable computer_cost and assign it a value of 2000.


# Declare a variable called total_cost that takes the sum of all costs above (excluding budget).


# Write an if statement that checks whether the sum of all our costs is within the budget.
# If so, print "You're total cost is " concatentated with the `total_cost` variable.
# Else, print "You're over budget by " concatenated with the difference between `budget` and `total_cost`.
        

# Write an if statement that checks whether the rent_cost is larger than the sum of the `utilities_cost`, `food_cost`,
# and `transportation_cost`. If so, print a string that says "The rent is too damn high!".
# Else, print a string that says "Ahhh just right!"

In [70]:

# Declare a variable named 'dog' with a string of "Spot".
dog = "Spot" 

# Declare 3 variables `cat`, `city`, `car` without assigning them values.
cat = ""
city = ""
car = ""
car = "Prius"
city = "San Franciso"
cat = "Farley"

print("See " + dog + " run!")
print("I drive " + cat + " around " + city + " in my " + car)
# Assign the string "Farley" to `cat`.


# Assign the string "San Francisco" to `city`.


# Assign the string "Prius" to `car`.


# Using string concatenation, print out the sentence "See Spot run!".


# Using string concatenation, print out the sentence "I drive Farley around San Francisco in my Prius".

See Spot run!
I drive Farley around San Franciso in my Prius

In [86]:
# Declare a variable budget and assign it a value of 5000.
budget = 5000
rent_cost = 1500
utilities_cost = 150
food_cost = 250
transportation_cost = 350
computer_cost = 2000
total_cost = rent_cost + utilities_cost + food_cost + transportation_cost + computer_cost
over =  budget - total_cost
utilities_etc = utilities_cost + food_cost + transportation_cost
print(over)
print(total_cost)

if total_cost < budget:
    print("Your total cost is:" + str(total_cost))
else:
    print("You're over budget by") 
    
if rent_cost > utilities_cost:
    print("The rent is too high")
else:
    print("aahhh just right")
    
    
    
# Write an if statement that checks whether the rent_cost is larger than the sum of the `utilities_cost`, `food_cost`,
# and `transportation_cost`. If so, print a string that says "The rent is too damn high!".
# Else, print a string that says "Ahhh just right!"

# Declare a variable rent_cost and assign it a value of 1500.


# Declare a variable utilities_cost and assign it a value of 150.


# Declare a variable food_cost and assign it a value of 250.


# Declare a variable transportation_cost and assign it a value of 350.


# Declare a variable computer_cost and assign it a value of 2000.


# Declare a variable called total_cost that takes the sum of all costs above (excluding budget).


# Write an if statement that checks whether the sum of all our costs is within the budget.
# If so, print "You're total cost is " concatentated with the `total_cost` variable.
# Else, print "You're over budget by " concatenated with the difference between `budget` and `total_cost`.

750
4250
Your total cost is:4250
The rent is too high

In [109]:
######################
# Create Character One
######################

# Make a variable called `c1_name` and have it equal a string of "Mr. Farley".

cl_name = "Mr Farley"
cl_age = 65
cl_profession = "Web Developer"
cl_salary = 100000
cl_species = "cat" 
cl_location = "San Francisco, CA"
cl_monthly_rent = 2000
cl_monthly_expenses = 1500
cl_yearly_rent = cl_monthly_rent * 12
cl_yearly_expenses = 1500.00 * 12
cl_savings = cl_salary - (cl_yearly_rent + cl_yearly_expenses)

######################
# Create Character Two
######################
c2_name = "Mr Snuggles"
c2_age = 30
c2_species = "mouse"
c2_profession = "Accountant"
c2_salary = 7000
c2_location = "Oakland, CA"
c2_monthly_rent = 4000
c2_monthly_expenses = 500
c2_yearly_rent = c2_monthly_rent * 12
c2_yearly_expenses = c2_monthly_expenses * 12
c2_savings = c2_salary - (c2_yearly_rent + c2_yearly_expenses)

##############
# Conditionals
##############

# Write an if-else statement to check if `c1_name` is equal to "Mr. Farley". If so, print a string of "Hello Mr. Farley" using the `c1_name` variable. If not, print a string of "Hello stranger".


# Write an if-else statement to check if `c2_age` is greater than `c1_age`. If so, print a string of "Mr. Farley is older than Mr. Snuggles". Else if `c1_age` is greater than `c2_age`, print a string of "Mr. Snuggles is older than Mr. Farley". Else, `c1_age` must have to be equal to `c2_age`, therefore print a string of "Mr. Farley is the same age as Mr. Snuggles".


# Write an if-else statement to check if `c1_location` is equal to "Oakland, CA". If so, print a string of "Mr. Farley comes from the home of the Raiders!". Else if `c1_location` is equal to a string of "San Francisco, CA", print a string of "Mr. Farley comes from the home of the 49ers!". Else both conditions must not apply and therefore print a string "Mr. Farley doesn't hail from a sports town."


# Write an if-else statement to check if `c1_monthly_rent` is greater than `c2_monthly_rent`. If so, print a string of "Mr. Farley pays more rent than Mr. Snuggles". Else if `c1_monthly_rent` is less than `c2_monthly_rent`, print a string of "Mr. Farley pays less rent than Mr. Snuggles". Else, `c1_monthly_rent` must have to be equal to `c2_monthly_rent`, therefore print a string of "Mr. Farley pays the same rent as Mr. Snuggles".


# Write an if-else statement to check if `c1_monthly_expenses` is greater than `c2_monthly_expenses`. If so, print a string of `Mr. Farley has more expenses than Mr. Snuggles`. Else if `c1_monthly_expenses` is less than `c2_monthly_expenses`, print a string of "Mr. Farley pays less expenses than Mr. Snuggles". Else, `c1_monthly_expenses` must have to be equal to `c2_monthly_expenses`, therefore print a string of "Mr. Farley pays the same expenses at Mr. Snuggles".


# Write an if-else statement to check if `c1_profession` is equal to "Web Developer" AND `c2_profession` is equal to "Accountant". If so, print a string of "Look a Web Developer and an Accountant", else print a string of "They are professionals."

if cl_name == "Mr Farley":
    print("Hello " + cl_name)
else:
    print("Hello Stranger")

if c2_age > cl_age:
    print(cl_name + "is older than " + c2_name)
elif cl_age > c2_age:
    print(c2_name + " is older than " + cl_name)
else:
    print(cl_name + " is the same age as " + c2_name)
    
if cl_location == "Oakland, CA":
    print(cl_name + " comes from the home of the raiders")
elif cl_location == "San Francisco, CA":
    print(cl_name + " comes from the home of the 49ers!")
else: 
    print(cl_name + " doesnt hail from sports towns")

Hello Mr Farley
Mr Snuggles is older than Mr Farley
Mr Farley comes from the home of the 49ers!